### ISSUE TITLE
rasusa subsampling bug

### ISSUE THREAD

**Issue by npbhavya** [beardymcjohnface/Trimnami#14]
Need to add the -n flag,  in the rasusa rule to subsample. 
   -n  {params.bases}

**Comment by beardymcjohnface** [comment]
ahh woops, the help messages says specify the number of reads but we're using --bases in the rule. Did you have a preference?

**Comment by npbhavya** [comment]
The way it is, just defining -subsample works well for phage genomes. For other genomes, I think its better to provide the option to pick the number of bases as well.

**Comment by beardymcjohnface** [comment]
This should be addressed in the next version. The config has examples for parsing different options.
