### ISSUE TITLE
Add cutadapt for fasta processing

### ISSUE THREAD

**Issue by linsalrob** [beardymcjohnface/Trimnami#8]
[fastp](https://github.com/OpenGene/fastp) only handles `fastq` files, while [cutadapt](https://cutadapt.readthedocs.io/en/stable/) can handle `fastq` and `fasta` files. There are times when you might want to trim out adapters from a fasta file (e.g. if you are downloading fasta from SRA).

**Comment by beardymcjohnface** [comment]
Added cutadapt using your barcodes file. trimnami will pass the fasta or fastq files verbatium and will rely on the trimmer to recognise fasta files or not (i think only cutadapt at the moment will work but havent tested). to make things easier on me, the cutadapt module will convert to fastq for the rest of the pipeline. You can pass the --fasta flag to trimnami to output fasta format files from ANY trimming module. So you would run something like this: `trimnami run cutadapt --reads readsDirectory/ --fasta`
